<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="ProductCatalog._Default" %>

<asp:Content runat="server" ID="FeaturedContent" ContentPlaceHolderID="FeaturedContent">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1><%: Title %>.</h1>
                <h2>Modify this template to jump-start your ASP.NET application.</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET, visit <a href="http://asp.net" title="ASP.NET Website">http://asp.net</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET.
                If you have any questions about ASP.NET visit
                <a href="http://forums.asp.net/18.aspx" title="ASP.NET Forum">our forums</a>.
            </p>
        </div>
    </section>
</asp:Content>
<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <table>
       <tr>
           <td colspan="2">
               <asp:Label ID="lblMesg" runat="server"></asp:Label>

           </td>
       </tr>
       <tr>
           <td><asp:TextBox ID="txtProductName" runat="server"></asp:TextBox></td>
       </tr>
       <tr>
           <td colspan="2">
              <asp:Button ID="btnSubmit" runat="server" Text="Add" OnClick="btnSubmit_Click" />
           </td>
       </tr>
   </table>
    <asp:GridView ID="grdData" runat="server" AutoGenerateColumns="False" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" >
        <Columns>
           <asp:BoundField DataField="Description" HeaderText="Task"/>
              <asp:BoundField DataField="IsDone" HeaderText="IsDone"/>
            <asp:BoundField DataField="ItemPosition" HeaderText="ItemPosition"/>
            <asp:BoundField DataField="ListColor" HeaderText="ListColor"/>
            <asp:BoundField DataField="CreateDt" HeaderText="CreateDt"/>

        </Columns>
    </asp:GridView>
   
  
   
</asp:Content>
